// <auto-generated />
using System;
using Hopeline.DataAccess.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hopeline.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190624230303_seedres")]
    partial class seedres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hopeline.DataAccess.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dateAdded");

                    b.Property<string>("desc");

                    b.Property<int>("enabled_flg");

                    b.Property<byte[]>("image");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("url")
                        .IsRequired();

                    b.Property<string>("user_code")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("communities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            dateAdded = "06-24-2019 19:03:03",
                            desc = "Descrption for community 1",
                            enabled_flg = 1,
                            title = "Community 1",
                            url = "www.google.ca",
                            user_code = "comm001"
                        },
                        new
                        {
                            Id = 2,
                            dateAdded = "06-24-2019 19:03:03",
                            desc = "Descrption for community 2",
                            enabled_flg = 0,
                            title = "Community 2",
                            url = "www.google.ca",
                            user_code = "comm002"
                        });
                });

            modelBuilder.Entity("Hopeline.DataAccess.Entities.Resource", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("dateAdded");

                    b.Property<string>("desc");

                    b.Property<int>("enabled_flg");

                    b.Property<byte[]>("image");

                    b.Property<int>("resource_categoryId");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("url")
                        .IsRequired();

                    b.Property<string>("user_code")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            dateAdded = "06-24-2019 19:03:03",
                            desc = "Descrpition for the resource",
                            enabled_flg = 1,
                            resource_categoryId = 1,
                            title = "Some resources",
                            url = "www.google.ca",
                            user_code = "res001"
                        },
                        new
                        {
                            Id = 2,
                            dateAdded = "06-24-2019 19:03:03",
                            desc = "Description for the res2",
                            enabled_flg = 0,
                            resource_categoryId = 2,
                            title = "Some title for res2",
                            url = "www.google.ca",
                            user_code = "res002"
                        },
                        new
                        {
                            Id = 3,
                            dateAdded = "06-24-2019 19:03:03",
                            desc = "Description for the res3",
                            enabled_flg = 0,
                            resource_categoryId = 3,
                            title = "Some title for res3",
                            url = "www.google.ca",
                            user_code = "res003"
                        });
                });

            modelBuilder.Entity("Hopeline.DataAccess.Entities.Resource_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("category_decription");

                    b.Property<string>("category_name")
                        .IsRequired();

                    b.Property<string>("dateAdded");

                    b.Property<string>("user_code")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("resource_categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            category_decription = "depression description",
                            category_name = "depression",
                            dateAdded = "06-24-2019 19:03:03",
                            user_code = "depre001"
                        },
                        new
                        {
                            Id = 2,
                            category_decription = "bullying description",
                            category_name = "bullying",
                            dateAdded = "06-24-2019 19:03:03",
                            user_code = "bully001"
                        },
                        new
                        {
                            Id = 3,
                            category_decription = "school-related description",
                            category_name = "school-related",
                            dateAdded = "06-24-2019 19:03:03",
                            user_code = "school001"
                        });
                });

            modelBuilder.Entity("Hopeline.DataAccess.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dateAdded");

                    b.Property<string>("desc");

                    b.Property<int>("enabled_flg");

                    b.Property<string>("topic_name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("user_code")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            dateAdded = "06-24-2019 19:03:03",
                            desc = "Despression is a mental disease",
                            enabled_flg = 1,
                            topic_name = "Depression",
                            user_code = "Drep001"
                        },
                        new
                        {
                            Id = 2,
                            dateAdded = "06-24-2019 19:03:03",
                            desc = "Bullying is bad",
                            enabled_flg = 1,
                            topic_name = "Bullying",
                            user_code = "Bullying001"
                        });
                });

            modelBuilder.Entity("Hopeline.DataAccess.Entities.Resource", b =>
                {
                    b.HasOne("Hopeline.DataAccess.Entities.Resource_Category", "resource_category")
                        .WithMany("resources")
                        .HasForeignKey("Id")
                        .HasConstraintName("Foreign_key_resource_category")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
